In [47]:
!pip install -r requirements.txt

Requirement already satisfied: pandas in .\mrs_env\Lib\site-packages (from -r requirements.txt (line 1)) (3.0.5)
Requirement already satisfied: numpy in .\mrs_env\Lib\site-packages (from -r requirements.txt (line 2)) (2.5.2)
Requirement already satisfied: scikit-learn in .\mrs_env\Lib\site-packages (from -r requirements.txt (line 3)) (1.9.0)
Requirement already satisfied: scipy in .\mrs_env\Lib\site-packages (from -r requirements.txt (line 4)) (1.18.0)
Requirement already satisfied: streamlit in .\mrs_env\Lib\site-packages (from -r requirements.txt (line 5)) (1.61.1)
Collecting matplotlib (from -r requirements.txt (line 6))
  Downloading matplotlib-3.11.1-cp313-cp313-win_amd64.whl.metadata (80 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in .\mrs_env\Lib\site-packages (from pandas->-r requirements.txt (line 1)) (2.9.0.post0)
Requirement already satisfied: tzdata in .\mrs_env\Lib\site-packages (from pandas->-r requirements.txt (line 1)) (2026.3)
Requirement already satisfied: joblib>=1.4.0 in .\mrs_env\Lib\site-packages (from scikit-learn->-r requirements.txt (line 3)) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in .\mrs_env\Lib\site-packages (from scikit-learn->-r requirements.txt (line 3)) (2.24.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in .\mrs_env\Lib\site-packages (from scikit-learn->-r requirements.txt (line 3)) (3.6.0)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=5.0.0 in .\mrs_env\Lib\site-packages (from streamlit->-r requirements.txt (line 5)) (6.2.2)
Requirement already satisfied: blinker<2,>=1.5.0 in .\mrs_env\Lib\site-packages (from streamlit->-r requirements.txt (line 5)) (1.9.0)
Requirement already satisfied: click<9,>=7.0 in .\mrs_env\Lib\site-packages (from streamlit->-r requirements.txt (line 5)) (8.4.2)
Requirement already satisfied: packaging>=20 in .\mrs_env\Lib\site-packages (from streamlit->-r requirements.txt (line 5)) (26.3)
Requirement already satisfied: pillow<13,>=7.1.0 in .\mrs_env\Lib\site-packages (from streamlit->-r requirements.txt (line 5)) (12.3.0)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in .\mrs_env\Lib\site-packages (from streamlit->-r requirements.txt (line 5)) (0.9.3)
Requirement already satisfied: protobuf<8,>=5.26.1 in .\mrs_env\Lib\site-packages (from streamlit->-r requirements.txt (line 5)) (7.35.1)
Requirement already satisfied: pyarrow<25,>=7.0 in .\mrs_env\Lib\site-packages (from streamlit->-r requirements.txt (line 5)) (24.0.0)
Requirement already satisfied: requests<3,>=2.27 in .\mrs_env\Lib\site-packages (from streamlit->-r requirements.txt (line 5)) (2.34.2)
Requirement already satisfied: tenacity<10,>=8.1.0 in .\mrs_env\Lib\site-packages (from streamlit->-r requirements.txt (line 5)) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in .\mrs_env\Lib\site-packages (from streamlit->-r requirements.txt (line 5)) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in .\mrs_env\Lib\site-packages (from streamlit->-r requirements.txt (line 5)) (4.16.0)
Requirement already satisfied: starlette<1.4.0,>=0.46.0 in .\mrs_env\Lib\site-packages (from streamlit->-r requirements.txt (line 5)) (1.3.1)
Requirement already satisfied: uvicorn<1,>=0.30.0 in .\mrs_env\Lib\site-packages (from streamlit->-r requirements.txt (line 5)) (0.52.3)
Requirement already satisfied: httptools<1,>=0.6.3 in .\mrs_env\Lib\site-packages (from streamlit->-r requirements.txt (line 5)) (0.8.0)
Requirement already satisfied: anyio<5,>=4.0.0 in .\mrs_env\Lib\site-packages (from streamlit->-r requirements.txt (line 5)) (4.14.2)
Requirement already satisfied: python-multipart<1,>=0.0.10 in .\mrs_env\Lib\site-packages (from streamlit->-r requirements.txt (line 5)) (0.0.32)
Requirement already satisfied: websockets<17,>=12.0.0 in .\mrs_env\Lib\site-packages (from streamlit->-r requirements.txt (line 5)) (16.1.1)
Requirement already satisfied: itsdangerous<3,>=2.1.2 in .\mrs_env\Lib\site-packages (from streamlit->-r requirements.txt (line 5)) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in .\mrs_env\Lib\site-packages (from streamlit->-r requirements.txt (line 5)) (6.0.0)
Requirement already satisfied: jinja2 in .\mrs_env\Lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit->-r requirements.txt (line 5)) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in .\mrs_env\Lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit->-r requirements.txt (line 5)) (4.26.0)
Requirement already satisfied: idna>=2.8 in .\mrs_env\Lib\site-packages (from anyio<5,>=4.0.0->streamlit->-r requirements.txt (line 5)) (3.18)
Requirement already satisfied: colorama in .\mrs_env\Lib\site-packages (from click<9,>=7.0->streamlit->-r requirements.txt (line 5)) (0.4.6)
Requirement already satisfied: charset_normalizer<4,>=2 in .\mrs_env\Lib\site-packages (from requests<3,>=2.27->streamlit->-r requirements.txt (line 5)) (3.5.1)
Requirement already satisfied: urllib3<3,>=1.26 in .\mrs_env\Lib\site-packages (from requests<3,>=2.27->streamlit->-r requirements.txt (line 5)) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in .\mrs_env\Lib\site-packages (from requests<3,>=2.27->streamlit->-r requirements.txt (line 5)) (2026.7.22)
Requirement already satisfied: h11>=0.8 in .\mrs_env\Lib\site-packages (from uvicorn<1,>=0.30.0->streamlit->-r requirements.txt (line 5)) (0.16.0)
Collecting contourpy>=1.0.1 (from matplotlib->-r requirements.txt (line 6))
  Using cached contourpy-1.3.3-cp313-cp313-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib->-r requirements.txt (line 6))
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.28.2 (from matplotlib->-r requirements.txt (line 6))
  Downloading fonttools-4.63.0-cp313-cp313-win_amd64.whl.metadata (121 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib->-r requirements.txt (line 6))
  Downloading kiwisolver-1.5.0-cp313-cp313-win_amd64.whl.metadata (5.2 kB)
Collecting pyparsing>=3 (from matplotlib->-r requirements.txt (line 6))
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: MarkupSafe>=2.0 in .\mrs_env\Lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit->-r requirements.txt (line 5)) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in .\mrs_env\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit->-r requirements.txt (line 5)) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in .\mrs_env\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit->-r requirements.txt (line 5)) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in .\mrs_env\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit->-r requirements.txt (line 5)) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in .\mrs_env\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit->-r requirements.txt (line 5)) (2026.6.3)
Requirement already satisfied: six>=1.5 in .\mrs_env\Lib\site-packages (from python-dateutil>=2.8.2->pandas->-r requirements.txt (line 1)) (1.17.0)
Downloading matplotlib-3.11.1-cp313-cp313-win_amd64.whl (9.3 MB)
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.3 MB 4.0 MB/s eta 0:00:03
   ---- ----------------------------------- 1.0/9.3 MB 2.8 MB/s eta 0:00:03
   ------ --------------------------------- 1.6/9.3 MB 2.5 MB/s eta 0:00:04
   ---------- ----------------------------- 2.4/9.3 MB 2.9 MB/s eta 0:00:03
   ------------- -------------------------- 3.1/9.3 MB 3.1 MB/s eta 0:00:02
   ---------------- ----------------------- 3.9/9.3 MB 3.2 MB/s eta 0:00:02
   -------------------- ------------------- 4.7/9.3 MB 3.3 MB/s eta 0:00:02
   ------------------------ --------------- 5.8/9.3 MB 3.5 MB/s eta 0:00:02
   ---------------------------- ----------- 6.6/9.3 MB 3.6 MB/s eta 0:00:01
   -------------------------------- ------- 7.6/9.3 MB 3.7 MB/s eta 0:00:01
   ----------------------------------- ---- 8.4/9.3 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------  9.2/9.3 MB 3.8 MB/s eta 0:00:01
   ---------------------------------------- 9.3/9.3 MB 3.7 MB/s  0:00:02
Using cached contourpy-1.3.3-cp313-cp313-win_amd64.whl (226 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.63.0-cp313-cp313-win_amd64.whl (2.3 MB)
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.3 MB ? eta -:--:--
   ------------- -------------------------- 0.8/2.3 MB 1.9 MB/s eta 0:00:01
   ----------------- ---------------------- 1.0/2.3 MB 1.9 MB/s eta 0:00:01
   -------------------------- ------------- 1.6/2.3 MB 2.1 MB/s eta 0:00:01
   ---------------------------------------- 2.3/2.3 MB 2.3 MB/s  0:00:01
Downloading kiwisolver-1.5.0-cp313-cp313-win_amd64.whl (73 kB)
Using cached pyparsing-3.3.2-py3-none-any.whl (122 kB)
Installing collected packages: pyparsing, kiwisolver, fonttools, cycler, contourpy, matplotlib

   ---------------------------------------- 0/6 [pyparsing]
   ------ --------------------------------- 1/6 [kiwisolver]
   ------------- -------------------------- 2/6 [fonttools]
   ------------- -------------------------- 2/6 [fonttools]
   ------------- -------------------------- 2/6 [fonttools]
   ------------- -------------------------- 2/6 [fonttools]
   ------------- -------------------------- 2/6 [fonttools]
   ------------- -------------------------- 2/6 [fonttools]
   ------------- -------------------------- 2/6 [fonttools]
   ------------- -------------------------- 2/6 [fonttools]
   ------------- -------------------------- 2/6 [fonttools]
   ------------- -------------------------- 2/6 [fonttools]
   ------------- -------------------------- 2/6 [fonttools]
   ------------- -------------------------- 2/6 [fonttools]
   ------------- -------------------------- 2/6 [fonttools]
   ------------- -------------------------- 2/6 [fonttools]
   ------------- -------------------------- 2/6 [fonttools]
   ------------- -------------------------- 2/6 [fonttools]
   ------------- -------------------------- 2/6 [fonttools]
   ------------- -------------------------- 2/6 [fonttools]
   ------------- -------------------------- 2/6 [fonttools]
   ------------- -------------------------- 2/6 [fonttools]
   ------------- -------------------------- 2/6 [fonttools]
   ------------- -------------------------- 2/6 [fonttools]
   ------------- -------------------------- 2/6 [fonttools]
   ------------- -------------------------- 2/6 [fonttools]
   ------------- -------------------------- 2/6 [fonttools]
   ------------- -------------------------- 2/6 [fonttools]
   ------------- -------------------------- 2/6 [fonttools]
   ------------- -------------------------- 2/6 [fonttools]
   ------------- -------------------------- 2/6 [fonttools]
   ------------- -------------------------- 2/6 [fonttools]
   -------------------------- ------------- 4/6 [contourpy]
   --------------------------------- ------ 5/6 [matplotlib]
   --------------------------------- ------ 5/6 [matplotlib]
   --------------------------------- ------ 5/6 [matplotlib]
   --------------------------------- ------ 5/6 [matplotlib]
   --------------------------------- ------ 5/6 [matplotlib]
   --------------------------------- ------ 5/6 [matplotlib]
   --------------------------------- ------ 5/6 [matplotlib]
   --------------------------------- ------ 5/6 [matplotlib]
   --------------------------------- ------ 5/6 [matplotlib]
   --------------------------------- ------ 5/6 [matplotlib]
   --------------------------------- ------ 5/6 [matplotlib]
   --------------------------------- ------ 5/6 [matplotlib]
   --------------------------------- ------ 5/6 [matplotlib]
   --------------------------------- ------ 5/6 [matplotlib]
   --------------------------------- ------ 5/6 [matplotlib]
   --------------------------------- ------ 5/6 [matplotlib]
   --------------------------------- ------ 5/6 [matplotlib]
   --------------------------------- ------ 5/6 [matplotlib]
   --------------------------------- ------ 5/6 [matplotlib]
   --------------------------------- ------ 5/6 [matplotlib]
   --------------------------------- ------ 5/6 [matplotlib]
   --------------------------------- ------ 5/6 [matplotlib]
   --------------------------------- ------ 5/6 [matplotlib]
   --------------------------------- ------ 5/6 [matplotlib]
   --------------------------------- ------ 5/6 [matplotlib]
   --------------------------------- ------ 5/6 [matplotlib]
   --------------------------------- ------ 5/6 [matplotlib]
   --------------------------------- ------ 5/6 [matplotlib]
   --------------------------------- ------ 5/6 [matplotlib]
   --------------------------------- ------ 5/6 [matplotlib]
   --------------------------------- ------ 5/6 [matplotlib]
   --------------------------------- ------ 5/6 [matplotlib]
   --------------------------------- ------ 5/6 [matplotlib]
   --------------------------------- ------ 5/6 [matplotlib]
   ---------------------------------------- 6/6 [matplotlib]

Successfully installed contourpy-1.3.3 cycler-0.12.1 fonttools-4.63.0 kiwisolver-1.5.0 matplotlib-3.11.1 pyparsing-3.3.2

In [161]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [162]:
data = pd.read_csv("data.csv")

# EDA & PREPROCESSING

In [163]:
data.head()

,valence,year,acousticness,artists,danceability,duration_ms,energy,explicit,id,instrumentalness,key,liveness,loudness,mode,name,popularity,release_date,speechiness,tempo
0,0.0594,1921,0.982,"['Sergei Rachmaninoff', 'James Levine', 'Berli...",0.279,831667,0.211,0,4BJqT0PrAfrxzMOxytFOIz,0.878000,10,0.665,-20.096,1,"Piano Concerto No. 3 in D Minor, Op. 30: III. ...",4,1921,0.0366,80.954
1,0.9630,1921,0.732,['Dennis Day'],0.819,180533,0.341,0,7xPhfUan2yNtyFG0cUWkt8,0.000000,7,0.160,-12.441,1,Clancy Lowered the Boom,5,1921,0.4150,60.936
2,0.0394,1921,0.961,['KHP Kridhamardawa Karaton Ngayogyakarta Hadi...,0.328,500062,0.166,0,1o6I8BglA6ylDMrIELygv1,0.913000,3,0.101,-14.850,1,Gati Bali,5,1921,0.0339,110.339
3,0.1650,1921,0.967,['Frank Parker'],0.275,210000,0.309,0,3ftBPsC5vPBKxYSee08FDH,0.000028,5,0.381,-9.316,1,Danny Boy,3,1921,0.0354,100.109
4,0.2530,1921,0.957,['Phil Regan'],0.418,166693,0.193,0,4d6HGyGT8e121BsdKmw9v6,0.000002,3,0.229,-10.096,1,When Irish Eyes Are Smiling,2,1921,0.0380,101.665

In [164]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 170653 entries, 0 to 170652
Data columns (total 19 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   valence           170653 non-null  float64
 1   year              170653 non-null  int64
 2   acousticness      170653 non-null  float64
 3   artists           170653 non-null  str
 4   danceability      170653 non-null  float64
 5   duration_ms       170653 non-null  int64
 6   energy            170653 non-null  float64
 7   explicit          170653 non-null  int64
 8   id                170653 non-null  str
 9   instrumentalness  170653 non-null  float64
 10  key               170653 non-null  int64
 11  liveness          170653 non-null  float64
 12  loudness          170653 non-null  float64
 13  mode              170653 non-null  int64
 14  name              170653 non-null  str
 15  popularity        170653 non-null  int64
 16  release_date      170653 non-null  str
 17  speechiness       170653 non-null  float64
 18  tempo             170653 non-null  float64
dtypes: float64(9), int64(6), str(4)
memory usage: 37.4 MB

In [165]:
data = data[['id', 'name', 'artists', 'year'] + [col for col in data.columns if col not in ['id', 'name', 'artists', 'year']]]

In [166]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 170653 entries, 0 to 170652
Data columns (total 19 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                170653 non-null  str
 1   name              170653 non-null  str
 2   artists           170653 non-null  str
 3   year              170653 non-null  int64
 4   valence           170653 non-null  float64
 5   acousticness      170653 non-null  float64
 6   danceability      170653 non-null  float64
 7   duration_ms       170653 non-null  int64
 8   energy            170653 non-null  float64
 9   explicit          170653 non-null  int64
 10  instrumentalness  170653 non-null  float64
 11  key               170653 non-null  int64
 12  liveness          170653 non-null  float64
 13  loudness          170653 non-null  float64
 14  mode              170653 non-null  int64
 15  popularity        170653 non-null  int64
 16  release_date      170653 non-null  str
 17  speechiness       170653 non-null  float64
 18  tempo             170653 non-null  float64
dtypes: float64(9), int64(6), str(4)
memory usage: 37.4 MB

In [167]:
data.shape

(170653, 19)

In [168]:
data.isnull().sum()

id                  0
name                0
artists             0
year                0
valence             0
acousticness        0
danceability        0
duration_ms         0
energy              0
explicit            0
instrumentalness    0
key                 0
liveness            0
loudness            0
mode                0
popularity          0
release_date        0
speechiness         0
tempo               0
dtype: int64

In [169]:
data.duplicated().sum()

np.int64(0)

In [170]:
data.columns

Index(['id', 'name', 'artists', 'year', 'valence', 'acousticness',
       'danceability', 'duration_ms', 'energy', 'explicit', 'instrumentalness',
       'key', 'liveness', 'loudness', 'mode', 'popularity', 'release_date',
       'speechiness', 'tempo'],
      dtype='str')

In [171]:
numeric_features = ['valence', 
            'acousticness', 
            'danceability', 
            'duration_ms', 
            'energy', 
            'instrumentalness', 
            'key', 
            'liveness', 
            'loudness', 
            'mode', 
            'popularity', 
            'speechiness', 
            'tempo']

In [172]:
cat_feature = 'artists'

In [173]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
from sklearn.feature_extraction.text import TfidfVectorizer

In [174]:
data_preprocess = ColumnTransformer([
    ('cat', TfidfVectorizer(), cat_feature),
    ('num', StandardScaler(), numeric_features)
], remainder='drop')

In [175]:
music_data = data_preprocess.fit_transform(data)

In [176]:
music_data

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2696860 stored elements and shape (170653, 25257)>

In [177]:
music_data.shape

(170653, 25257)

# BUILDING & TESTING MODEL

In [178]:
from sklearn.metrics.pairwise import cosine_similarity

In [179]:
idx = data[data['name'].str.lower() == 'on the low'].index[0]

In [180]:
target_vector = music_data[idx:idx+1]
similarity_scores = cosine_similarity(target_vector, music_feat).flatten()

In [181]:
similarity_scores[idx] = -1.0

In [182]:
top_indices = np.argpartition(similarity_scores, -10)[-10:]
top_indices = top_indices[np.argsort(similarity_scores[top_indices])[::-1]]

recommendations = data.iloc[top_indices][['name', 'artists', 'year']]

In [183]:
recommendations

,name,artists,year
74616,Shape of You,['Ed Sheeran'],2017
19074,Shape of You,['Ed Sheeran'],2017
90696,Baby I'm Yours,"['Breakbot', 'Irfane']",2012
11208,Beast Of Burden - Remastered,['The Rolling Stones'],1978
108604,El Efecto,"['Rauw Alejandro', 'Chencho Corleone']",2019
36635,Baby I'm Yours,"['Breakbot', 'Irfane']",2010
55195,La Isla Bonita,['Madonna'],2009
108654,El Buho,['Luis R Conriquez'],2019
53880,Métele Sazón,"['Luny Tunes', 'Noriega', 'Tego Calderon']",2003
108643,Detention,['Melanie Martinez'],2019

# CREATING A FUNCTION OF MODEL

In [184]:
def recommend_song(song_name, no_of_recommendations = 5, data_frame = data, feature_matrix = music_data):
    matches = data[data['name'].str.lower() == (song_name.lower().strip())]

    if matches.empty:
        return f"Error: '{song_name}' not found in the dataset."
        
    idx = matches.index[0]

    target_vector = music_data[idx:idx+1]
    similarity_scores = cosine_similarity(target_vector, music_feat).flatten()

    similarity_scores[idx] = -1

    top_indices = np.argpartition(similarity_scores, -(no_of_recommendations))[-no_of_recommendations:]
    top_indices = top_indices[np.argsort(similarity_scores[top_indices])[::-1]]

    recommendations = data.iloc[top_indices][['name', 'artists', 'year']]

    return recommendations

In [185]:
recommend_song('runaway', 10)

,name,artists,year
55888,Modern Jesus,['Portugal. The Man'],2013
155414,telepatía,['Kali Uchis'],2020
35613,El Listón De Tu Pelo,['Los Ángeles Azules'],2005
169700,Dangerous,['Royal Deluxe'],2016
160695,Dieci ragazze,['Lucio Battisti'],1970
34618,Help! - Remastered 2015,['The Beatles'],2000
9115,Lovely Rita - Remastered 2009,['The Beatles'],1967
75075,4 Thangs (feat. Big Sean & Hit-Boy),"['Freddie Gibbs', 'Hit-Boy', 'Big Sean']",2020
35593,Cómo Te Voy A Olvidar,['Los Ángeles Azules'],2005
123753,Smooth Sailin',['Leon Bridges'],2015

# SAVING REQUIRED DATA

In [186]:
import joblib
from scipy.sparse import save_npz

In [188]:
df_metadata = data[['name','artists','year','popularity']].reset_index(drop=True)

In [189]:
joblib.dump(df_metadata, 'music_metadata.pkl') #for storing metadata about dataframe 

save_npz('music_matrix.npz', music_data) #for storing the sparse matrix generated after preprocessing

joblib.dump(data_preprocess, 'preprocessor.pkl') #for storing the preprocessor (ColumnTransformer)

print("Success: `music_metadata.pkl`, `music_feat.npz` and `preprocessor.pkl` have been saved successfully!")

Success: `music_metadata.pkl`, `music_feat.npz` and `preprocessor.pkl` have been saved successfully!